import { db } from './firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';

const employeeData = [
  {
    "employeeId": "1",
    "joiningDate": "1-Nov-2023",
    "name": "Ahmed Sadiq",
    "endingDate": "1-Jan-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp1@hostajournal.biz"
  },
  {
    "employeeId": "2",
    "joiningDate": "1-Apr-2024",
    "name": "Bilal Akram",
    "endingDate": "2-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp2@hostajournal.biz"
  },
  {
    "employeeId": "3",
    "joiningDate": "1-Feb-2024",
    "name": "Shaheer",
    "endingDate": "2-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp3@hostajournal.biz"
  },
  {
    "employeeId": "4",
    "joiningDate": "14-Feb-2024",
    "name": "Hassam Shafiq",
    "endingDate": "11-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp4@hostajournal.biz"
  },
  {
    "employeeId": "5",
    "joiningDate": "3-May-2024",
    "name": "Ahtisham Asghar",
    "modeOfWorking": "ON Site",
    "cnic": "35103-7717684-3",
    "whatsappPersonal": "92-300-9445243",
    "address": "AL-kHAIR CITY PATTOKI",
    "gender": "Male",
    "endingDate": "1-Jun-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp5@hostajournal.biz"
  },
  {
    "employeeId": "6",
    "joiningDate": "1-May-2024",
    "name": "Tahir Mahmood",
    "officialMail": "tahirmehmood3755@gmail.com",
    "cnic": "35103-6913890-5",
    "whatsappPersonal": "92-324-4491053",
    "homePhone": "92-301-6802856",
    "address": "Pattoki Badar Colony",
    "qualification": "FSC (Medical)",
    "gender": "Male",
    "remarks": "CV Missing",
    "endingDate": "30-Jun-2025",
    "role": "Employee",
    "points": 0,
    "email": "tahirmehmood3755@gmail.com"
  },
  {
    "employeeId": "7",
    "joiningDate": "1-May-2024",
    "name": "Khizar Ali",
    "modeOfWorking": "ON Site",
    "assignments": "Articles Generating",
    "personalEmail": "khizara845@gmail.com",
    "cnic": "35103-3321919-9",
    "whatsappPersonal": "92-329-8047813",
    "homePhone": "92-324-4516190",
    "address": "Bhaidian chuk no 35 Pattoki",
    "qualification": "FSC (Engineering)",
    "gender": "Male",
    "endingDate": "31-Jul-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "khizara845@gmail.com"
  },
  {
    "employeeId": "8",
    "joiningDate": "1-May-2024",
    "name": "Zohaib Jamshaid",
    "modeOfWorking": "ON Site",
    "personalEmail": "zohaibjamshad.pakistan@gmail.com",
    "cnic": "35101-2757245-1",
    "whatsappPersonal": "92-328-0443619",
    "homePhone": "92-300-4845930",
    "address": "Shadman colony Pattoki",
    "qualification": "BSCS (Continue)",
    "gender": "Male",
    "endingDate": "12-Jul-2025",
    "role": "Employee",
    "points": 0,
    "email": "zohaibjamshad.pakistan@gmail.com"
  },
  {
    "employeeId": "9",
    "joiningDate": "7-May-2024",
    "name": "Farooq Raza",
    "modeOfWorking": "ON Site",
    "personalEmail": "faroqraza042@gmail.com",
    "whatsappPersonal": "92-302-4060951",
    "address": "Pattoki Old Mandi",
    "qualification": "F.A",
    "gender": "Male",
    "endingDate": "20-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "faroqraza042@gmail.com"
  },
  {
    "employeeId": "10",
    "joiningDate": "7-May-2024",
    "name": "Ali Hussnain",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-300-0435428",
    "address": "Pattoki Old Mandi",
    "gender": "Male",
    "endingDate": "2-Jun-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp10@hostajournal.biz"
  },
  {
    "employeeId": "11",
    "joiningDate": "9-May-2024",
    "name": "Husnain Asghar",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-300-9445235",
    "address": "AL-KHAIR CITY PATTOKI",
    "gender": "Male",
    "endingDate": "4-Jun-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp11@hostajournal.biz"
  },
  {
    "employeeId": "12",
    "joiningDate": "10-May-2024",
    "name": "Muhammad Waqas",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-300-5084367",
    "address": "Bakar Mandi",
    "gender": "Male",
    "endingDate": "13-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp12@hostajournal.biz"
  },
  {
    "employeeId": "13",
    "joiningDate": "11-May-2024",
    "name": "Atif Shakoor",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-3174226756",
    "address": "Shadman colony Pattoki",
    "gender": "Male",
    "endingDate": "13-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp13@hostajournal.biz"
  },
  {
    "employeeId": "14",
    "joiningDate": "11-May-2024",
    "name": "Junaid Zubair",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-300-6570160",
    "address": "vaa khara",
    "gender": "Male",
    "endingDate": "17-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp14@hostajournal.biz"
  },
  {
    "employeeId": "15",
    "joiningDate": "11-May-2024",
    "name": "Usama Rasool",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-302-8131101",
    "address": "vaa khara",
    "gender": "Male",
    "endingDate": "17-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp15@hostajournal.biz"
  },
  {
    "employeeId": "16",
    "joiningDate": "11-May-2024",
    "name": "Abdur Rahman",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-325-0030011",
    "address": "vaa khara",
    "gender": "Male",
    "endingDate": "17-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp16@hostajournal.biz"
  },
  {
    "employeeId": "17",
    "joiningDate": "13-May-2024",
    "name": "Imran Haidar",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-326-0764228",
    "address": "Pattoki kohna",
    "gender": "Male",
    "endingDate": "29-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp17@hostajournal.biz"
  },
  {
    "employeeId": "18",
    "joiningDate": "14-May-2024",
    "name": "Zohaib Sami",
    "modeOfWorking": "ON Site",
    "cnic": "35103-4318543-5",
    "whatsappPersonal": "92-321-4281402",
    "address": "Pattoki Old Mandi",
    "gender": "Male",
    "endingDate": "3-Jun-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp18@hostajournal.biz"
  },
  {
    "employeeId": "19",
    "joiningDate": "14-May-2024",
    "name": "Hussnain Ghulam Nabi",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-311-6457011",
    "gender": "Male",
    "endingDate": "17-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp19@hostajournal.biz"
  },
  {
    "employeeId": "20",
    "joiningDate": "15-May-2024",
    "name": "Daod",
    "modeOfWorking": "ON Site",
    "gender": "Male",
    "endingDate": "22-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp20@hostajournal.biz"
  },
  {
    "employeeId": "21",
    "joiningDate": "21-May-2024",
    "name": "Hamid Iqbal",
    "modeOfWorking": "ON Site",
    "cnic": "35103-9286982-1",
    "whatsappPersonal": "92-307-2322672",
    "address": "Shadman colony Pattoki",
    "gender": "Male",
    "endingDate": "22-May-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp21@hostajournal.biz"
  },
  {
    "employeeId": "22",
    "joiningDate": "6-Aug-2024",
    "name": "Syed Afzal Shah",
    "modeOfWorking": "ON Site",
    "personalEmail": "afzaljee186@gmail.com",
    "cnic": "35103-4418686-5",
    "whatsappPersonal": "92-328-6900140",
    "address": "Muzamel Bazar Gali No 10",
    "qualification": "BA (Islamiyat)",
    "gender": "Male",
    "endingDate": "24-Mar-2025",
    "role": "Employee",
    "points": 0,
    "email": "afzaljee186@gmail.com"
  },
  {
    "employeeId": "23",
    "joiningDate": "26-Aug-2024",
    "name": "Numan Abu Zar",
    "modeOfWorking": "ON Site",
    "cnic": "35103-6472185-3",
    "whatsappPersonal": "92-333-1403825",
    "gender": "Male",
    "endingDate": "13-Mar-2025",
    "role": "Employee",
    "points": 0,
    "email": "emp23@hostajournal.biz"
  },
  {
    "employeeId": "24",
    "joiningDate": "28-Aug-2024",
    "name": "Muhammad Abdullah",
    "modeOfWorking": "ON Site",
    "cnic": "35103-4523701-5",
    "whatsappPersonal": "92-323-1840850",
    "address": "Mohallah Malik Pura",
    "qualification": "Matric (Science)",
    "gender": "Male",
    "endingDate": "30-Sep-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp24@hostajournal.biz"
  },
  {
    "employeeId": "25",
    "joiningDate": "14-Sep-2024",
    "name": "Tabir Ali",
    "modeOfWorking": "ON Site",
    "cnic": "35103-4808284-1",
    "whatsappPersonal": "92-325-2593923",
    "gender": "Male",
    "remarks": "Confirm Same Name",
    "endingDate": "30-Sep-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp25@hostajournal.biz"
  },
  {
    "employeeId": "26",
    "joiningDate": "22-Sep-2024",
    "name": "CHAND AKRAM",
    "modeOfWorking": "ON Site",
    "assignments": "KJMR + Article Formating + Uplaoding",
    "officialMail": "chandakram1133@gmail.com",
    "personalEmail": "chandakram461@gmail.com",
    "cnic": "35103-6865650-9",
    "whatsappPersonal": "92-300-0917734",
    "homePhone": "92-302-6542405",
    "address": "Old mandi chunia road house no 32/5",
    "qualification": "ADP (CS)",
    "gender": "Male",
    "endingDate": "8-Dec-2025",
    "experience": "Fesh",
    "role": "Employee",
    "points": 0,
    "email": "chandakram461@gmail.com"
  },
  {
    "employeeId": "27",
    "joiningDate": "1-Oct-2024",
    "name": "Hafiz Hamza ",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-324-6551553",
    "gender": "Male",
    "endingDate": "3-Nov-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp27@hostajournal.biz"
  },
  {
    "employeeId": "28",
    "joiningDate": "1-Oct-2024",
    "name": "HAFIZ ABDULLAH",
    "modeOfWorking": "ON Site",
    "assignments": "OLD > NEW",
    "officialMail": "muhammad002360@gmail.com",
    "personalEmail": "abdullahsaifee002@gmail.com",
    "cnic": "35103-3471777-7",
    "whatsappPersonal": "92-301-7960291",
    "homePhone": "92-340-4144251",
    "address": "shadman colony street no 5 house no 9",
    "qualification": "MATRIC HIFAZ",
    "gender": "Male",
    "endingDate": "8-Dec-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "abdullahsaifee002@gmail.com"
  },
  {
    "employeeId": "29",
    "joiningDate": "1-Oct-2024",
    "name": "Tabarr Shair Ali",
    "modeOfWorking": "ON Site",
    "personalEmail": "tabarrsandhu@gmail.com",
    "cnic": "35103-1346558-7",
    "whatsappPersonal": "92-312-4675747",
    "address": "Kohna Road Pattoki",
    "qualification": "Intermadiate",
    "gender": "Male",
    "remarks": "Confirm Same Name",
    "endingDate": "1-Jul-2025",
    "role": "Employee",
    "points": 0,
    "email": "tabarrsandhu@gmail.com"
  },
  {
    "employeeId": "30",
    "joiningDate": "10-Oct-2024",
    "name": "Asad Ali Arshad",
    "modeOfWorking": "ON Site",
    "personalEmail": "asad.uiux1@gmail.com",
    "cnic": "35103-6656033-1",
    "whatsappPersonal": "92-322-4650142",
    "address": "Bilal Colony Pattoki",
    "qualification": "Intermadiate",
    "gender": "Male",
    "endingDate": "1-Nov-2024",
    "role": "Employee",
    "points": 0,
    "email": "asad.uiux1@gmail.com"
  },
  {
    "employeeId": "31",
    "joiningDate": "12-Oct-2024",
    "name": "Aqib Shakoor",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-317-4226756",
    "gender": "Male",
    "endingDate": "4-Nov-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp31@hostajournal.biz"
  },
  {
    "employeeId": "32",
    "joiningDate": "15-Oct-2024",
    "name": "Muhammad Aqib Nazir",
    "modeOfWorking": "ON Site",
    "personalEmail": "aqib3797@gmail.com",
    "cnic": "35103-6713014-1",
    "whatsappPersonal": "92-348-6799224",
    "address": "Daokey Chak 9 Pattoki",
    "qualification": "BS (Islamic study)",
    "gender": "Male",
    "endingDate": "22-Oct-2024",
    "role": "Employee",
    "points": 0,
    "email": "aqib3797@gmail.com"
  },
  {
    "employeeId": "33",
    "joiningDate": "15-Oct-2024",
    "name": "Muhammad  Ahmad",
    "modeOfWorking": "ON Site",
    "personalEmail": "ahmadrazzaq2244@gmail.com",
    "cnic": "35103-6387236-5",
    "whatsappPersonal": "92-301-4397619",
    "address": "Shadman colony Pattoki",
    "qualification": "Matric",
    "gender": "Male",
    "endingDate": "17-Nov-2024",
    "role": "Employee",
    "points": 0,
    "email": "ahmadrazzaq2244@gmail.com"
  },
  {
    "employeeId": "34",
    "joiningDate": "19-Oct-2024",
    "name": "Ali Hamza",
    "modeOfWorking": "ON Site",
    "personalEmail": "ALIhamzashahzad028@gmail.com",
    "whatsappPersonal": "92-300-4646694",
    "address": "Kohna Road Pattoki",
    "qualification": "ICOM",
    "gender": "Male",
    "endingDate": "5-Nov-2024",
    "role": "Employee",
    "points": 0,
    "email": "ALIhamzashahzad028@gmail.com"
  },
  {
    "employeeId": "35",
    "joiningDate": "21-Oct-2024",
    "name": "Ali Zain",
    "modeOfWorking": "ON Site",
    "cnic": "35103-8769568-5",
    "whatsappPersonal": "92-301-4743120",
    "address": "Kot Fazal Din,Pattoki",
    "qualification": "ICS (continue)",
    "gender": "Male",
    "endingDate": "23-Oct-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp35@hostajournal.biz"
  },
  {
    "employeeId": "36",
    "joiningDate": "22-Oct-2024",
    "name": "Umair Munir",
    "modeOfWorking": "ON Site",
    "cnic": "35302-3472808-7",
    "whatsappPersonal": "92-304-8881420",
    "address": "shadman colony street no 6 Pattoki",
    "qualification": "F.A",
    "gender": "Male",
    "endingDate": "28-Oct-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp36@hostajournal.biz"
  },
  {
    "employeeId": "37",
    "joiningDate": "24-Nov-2024",
    "name": "Muhammad Kashif Jabbar",
    "modeOfWorking": "ON Site",
    "gender": "Male",
    "endingDate": "25-Nov-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp37@hostajournal.biz"
  },
  {
    "employeeId": "38",
    "joiningDate": "2-Dec-2024",
    "name": "ZOHAIB JAVED",
    "assignments": "Remotely (25 Artcile Genarte + Formatting + Uplaoding)/ 1000PKR",
    "personalEmail": "zohaibjaved4145@gmail.com",
    "cnic": "35103-9017458-7",
    "whatsappPersonal": "92-308-0006504",
    "homePhone": "92-317-3360043",
    "address": "Muhala malik pura street no/ 02",
    "qualification": "BSCS (continue)",
    "gender": "Male",
    "remarks": "🔑",
    "endingDate": "31-Jul-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "zohaibjaved4145@gmail.com"
  },
  {
    "employeeId": "39",
    "joiningDate": "3-Dec-2024",
    "name": "Ali Sadar",
    "modeOfWorking": "ON Site",
    "whatsappPersonal": "92-327-0579742",
    "gender": "Male",
    "endingDate": "11-Dec-2024",
    "role": "Employee",
    "points": 0,
    "email": "emp39@hostajournal.biz"
  },
  {
    "employeeId": "40",
    "joiningDate": "13-Jan-2025",
    "name": "Numan Bashir",
    "modeOfWorking": "ON Site",
    "cnic": "35103-7480116-3",
    "whatsappPersonal": "92-329-4139001",
    "address": "Hallah Road Insaf City Pattoki",
    "qualification": "Intermediate (ICS)",
    "gender": "Male",
    "endingDate": "15-Apr-2025",
    "role": "Employee",
    "points": 0,
    "email": "emp40@hostajournal.biz"
  },
  {
    "employeeId": "41",
    "joiningDate": "19-Jan-2025",
    "name": "Abdullah Usman",
    "modeOfWorking": "ON Site",
    "gender": "Male",
    "endingDate": "31-Jan-2025",
    "role": "Employee",
    "points": 0,
    "email": "emp41@hostajournal.biz"
  },
  {
    "employeeId": "42",
    "joiningDate": "6-Feb-2025",
    "name": "JUNAID ABID",
    "assignments": "Old To New 100 Article / 1000PKR",
    "personalEmail": "junaidbhai557@gmail.com",
    "cnic": "34602-8681187-7",
    "whatsappPersonal": "92-328-6544878",
    "homePhone": "92-300-4938235",
    "address": "Sugar Mill Colony House No B/7",
    "qualification": "BSCS (continue)",
    "gender": "Male",
    "endingDate": "31-Jul-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "junaidbhai557@gmail.com"
  },
  {
    "employeeId": "43",
    "joiningDate": "14-Feb-2025",
    "name": "Ali Shan",
    "assignments": "Articles Generating",
    "personalEmail": "marvelouseshann@gmail.com",
    "cnic": "35103-4049486-5",
    "whatsappPersonal": "92-325-4559012",
    "homePhone": "92-304-4717028",
    "address": "Pattoki Kareem Park",
    "qualification": "Intermediate",
    "gender": "Male",
    "endingDate": "11-Jul-2025",
    "role": "Employee",
    "points": 0,
    "email": "marvelouseshann@gmail.com"
  },
  {
    "employeeId": "44",
    "joiningDate": "12-Apr-2025",
    "name": "Mubeen Ahmad",
    "modeOfWorking": "ON Site",
    "assignments": "OJS Backup + Hosting + Visit Old Journals +Template Downlaod + Check Indexing",
    "officialMail": "mubeenahmad09870@gmail.com",
    "personalEmail": "shkmubeen87@gmail.com",
    "cnic": "35103-4214752-5",
    "whatsappPersonal": "92-303-5903842",
    "homePhone": "92-328-6544817",
    "address": "Madina Colony Street No/03 Near Paragon School",
    "qualification": "MIDDLE",
    "gender": "Male",
    "endingDate": "8-Dec-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "shkmubeen87@gmail.com"
  },
  {
    "employeeId": "45",
    "joiningDate": "16-Apr-2025",
    "name": "Tasveeb Shahid",
    "assignments": "Remotely (30 Artcile Genarte + Formatting + Uplaoding)",
    "officialMail": "tasveeb.shahid@hostajournal.biz",
    "personalEmail": "hassanshahidb01@gmail.com",
    "cnic": "35103-7809064-8",
    "whatsappPersonal": "92-309-5151069",
    "homePhone": "92-300-6588101",
    "address": "Pattoki Old Mandi",
    "qualification": "Metric",
    "gender": "Female",
    "endingDate": "9-Aug-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "hassanshahidb01@gmail.com"
  },
  {
    "employeeId": "46",
    "joiningDate": "16-Apr-2025",
    "name": "Sana Abdul Guffar",
    "modeOfWorking": "ON Site",
    "assignments": "OJS Marketing Department",
    "officialMail": "sanaabbas0728@gmail.com",
    "personalEmail": "khair2002ali@gmail.com",
    "cnic": "35103-2637941-4",
    "whatsappPersonal": "92-328-9048785",
    "homePhone": "92-307-6803722",
    "address": "Pattoki Old Mandi",
    "qualification": "Intermediate",
    "gender": "Female",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "khair2002ali@gmail.com"
  },
  {
    "employeeId": "47",
    "joiningDate": "21-Apr-2025",
    "name": "Fakhira Batool",
    "modeOfWorking": "ON Site",
    "assignments": "OJS Complete  + Concents Team + 1PageCV + CV Database + Office Management  + Marketing",
    "officialMail": "fakhirabatool.009@gmail.com",
    "personalEmail": "fakhirak53@gmail.com",
    "cnic": "35103-10725496",
    "whatsappPersonal": "92-311-6463976",
    "homePhone": "92-303-4033359",
    "address": "Pattoki Bilal Colony",
    "qualification": "BS Information Technology",
    "gender": "Female",
    "experience": "Online Sale Purchase + Digital Marketing (2021)",
    "role": "Employee",
    "points": 0,
    "email": "fakhirak53@gmail.com"
  },
  {
    "employeeId": "48",
    "joiningDate": "26-Apr-2025",
    "name": "Sadia Yousaf",
    "modeOfWorking": "ON Site",
    "assignments": "Citation",
    "officialMail": "Sadiayousaf855@gmail.com",
    "personalEmail": "-",
    "cnic": "35103-51943802",
    "whatsappPersonal": "92-309-4435758",
    "homePhone": "92-303-4927570",
    "address": "Pattoki Madina Masjid Old Mandi",
    "qualification": "Matric",
    "gender": "Female",
    "remarks": "🔑",
    "endingDate": "15-Jan-2026",
    "experience": "EFA School System (2021)",
    "role": "Employee",
    "points": 0,
    "email": "Sadiayousaf855@gmail.com"
  },
  {
    "employeeId": "49",
    "joiningDate": "1-May-2025",
    "name": "Nabeel Anwar",
    "modeOfWorking": "ON Site",
    "assignments": " Formatting + Uplaoding + OLD / NEW",
    "officialMail": "nabeel.anwar@hostajournal.biz",
    "personalEmail": "saeedalisaeed@gmail.com",
    "cnic": "35103-2207723-9",
    "whatsappPersonal": "92-302-1556749",
    "homePhone": "92-303-2494009",
    "address": "P/O Khas Chak no 45 Padhana Pattoki",
    "qualification": "FSC (Medical)",
    "gender": "Male",
    "endingDate": "16-Oct-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "saeedalisaeed@gmail.com"
  },
  {
    "employeeId": "50",
    "joiningDate": "3-May-2025",
    "name": "Hafiz Zunair",
    "modeOfWorking": "ON Site",
    "personalEmail": "Zunairhafiz774@gmail.com",
    "cnic": "35103-0692519-3",
    "whatsappPersonal": "92-303-8976567",
    "address": "AlAhmed Town Allama Iqbal Road Pattoki",
    "qualification": "BSCS (continue)",
    "gender": "Male",
    "endingDate": "19-May-2025",
    "role": "Employee",
    "points": 0,
    "email": "Zunairhafiz774@gmail.com"
  },
  {
    "employeeId": "51",
    "joiningDate": "5-May-2025",
    "name": "Sawera Riasat",
    "assignments": "Remotely SCOPUS + DOAJ + WOS (Article Publication)",
    "officialMail": "sawera.riasat@hostajournal.biz",
    "personalEmail": "qamarjuttjutt939@gmail.com",
    "cnic": "35103-8173314-4",
    "whatsappPersonal": "92-328-0224893",
    "homePhone": "92-328-0224893",
    "address": "Pattoki Badar Colony",
    "qualification": "B.Ed (Continue)",
    "gender": "Female",
    "endingDate": "30-Jun-2025",
    "experience": "HBL Microfinance (Jul2025)",
    "role": "Employee",
    "points": 0,
    "email": "qamarjuttjutt939@gmail.com"
  },
  {
    "employeeId": "52",
    "joiningDate": "27-May-2025",
    "name": "Tayyaba Riasat",
    "assignments": "Indexing + Google Scholar Indexing + Citescore Increase + DOAJ SCOPUS Indexing",
    "officialMail": "tayyaba.riasat@hostajournal.biz",
    "personalEmail": "qamarjuttjutt939@gmail.com",
    "cnic": "35103-6298518-6",
    "whatsappPersonal": "92-317-7457847",
    "homePhone": "92-328-0224893",
    "address": "Pattoki Badar Colony",
    "qualification": "FSC",
    "gender": "Female",
    "endingDate": "1-Nov-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "qamarjuttjutt939@gmail.com"
  },
  {
    "employeeId": "53",
    "joiningDate": "27-May-2025",
    "name": "Tobba Riasat",
    "assignments": "Formatting + Uplaoding Article (Old/New)",
    "officialMail": "tobba.riasat@hostajournal.biz",
    "personalEmail": "qamarjuttjutt939@gmail.com",
    "cnic": "35103-6298613-6",
    "whatsappPersonal": "92-317-7457847",
    "homePhone": "92-328-0224893",
    "address": "Pattoki Badar Colony",
    "qualification": "Matric",
    "gender": "Female",
    "endingDate": "9-Aug-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "qamarjuttjutt939@gmail.com"
  },
  {
    "employeeId": "54",
    "joiningDate": "4-Jun-2025",
    "name": "Rabia Khalid J",
    "modeOfWorking": "ON Site",
    "assignments": "DOI + Manage Subscriptions + Office Expenses + Profit $ Loss Monthly + ZOHO",
    "officialMail": "hostajournal12@gmail.com",
    "personalEmail": "bia.rajpoot97@gmail.com",
    "cnic": "35103-9385656-8",
    "whatsappPersonal": "92-301-4084397",
    "homePhone": "92-300-4430197",
    "address": "Pattoki Darbar Stop",
    "qualification": "BBIT",
    "gender": "Female",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "bia.rajpoot97@gmail.com"
  },
  {
    "employeeId": "55",
    "joiningDate": "4-Jun-2025",
    "name": "Bushra Khalid",
    "modeOfWorking": "ON Site",
    "assignments": "DOAJ + OJS Review Form + Reviews (Current, Before) + Reviewers",
    "officialMail": "Bushrakhalid6780@gmail.com",
    "personalEmail": "bia.rajpoot97@gmail.com",
    "cnic": "35103-323687-4",
    "whatsappPersonal": "92-300-0893748",
    "homePhone": "92-300-4430197",
    "address": "Pattoki Darbar Stop",
    "qualification": "MA (Islamiyat)",
    "gender": "Female",
    "experience": "EFA School System (2011)",
    "role": "Employee",
    "points": 0,
    "email": "Bushrakhalid6780@gmail.com"
  },
  {
    "employeeId": "56",
    "joiningDate": "21-Jun-2025",
    "name": "Omar Farooq",
    "modeOfWorking": "ON Site",
    "assignments": "OJS Backup + Hosting + Visit Old Journals (Template Downlaod + Check Indexing + CSS File)",
    "officialMail": "omarfarooq6926@gmail.com",
    "personalEmail": "jumer3503@gmail.com",
    "cnic": "35103-4393810-1",
    "whatsappPersonal": "92-317-7436474",
    "homePhone": "92-308-0006504",
    "address": "Madina Colony Street No/03 Near Paragon School",
    "qualification": "ICS",
    "gender": "Male",
    "endingDate": "8-Dec-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "omarfarooq6926@gmail.com"
  },
  {
    "employeeId": "57",
    "joiningDate": "23-Jun-2025",
    "name": "Wisha Noor",
    "assignments": "Remotely (30 Artcile Genarte + Formatting + Uplaoding)",
    "officialMail": "wisha.noor@hostajournal.biz",
    "personalEmail": "786wishanoor@gmail.com",
    "cnic": "32202-5510514-0",
    "whatsappPersonal": "92-329-7311713",
    "homePhone": "92-341-6669555",
    "address": "Burj Mahalam, Chak 35, Pattoki",
    "qualification": "BSCS",
    "gender": "Female",
    "endingDate": "9-Aug-2025",
    "experience": "DarArqam (Dec 2023)",
    "role": "Employee",
    "points": 0,
    "email": "786wishanoor@gmail.com"
  },
  {
    "employeeId": "58",
    "joiningDate": "18-Jun-2025",
    "name": "Sadia Zulifqar",
    "modeOfWorking": "Remotely",
    "assignments": "50 Indexing Links",
    "officialMail": "sadia.zulifqar@hostajournal.biz",
    "personalEmail": "sadiazulfiqar870@gmail.com",
    "cnic": "35101-8765028-4",
    "whatsappPersonal": "92-314-1774838",
    "homePhone": "92-328-4172731",
    "address": "Alhamad Town, Pattoki",
    "qualification": "MA. English",
    "gender": "Female",
    "endingDate": "04-Aug-2025",
    "experience": "Online",
    "role": "Employee",
    "points": 0,
    "email": "sadiazulfiqar870@gmail.com"
  },
  {
    "employeeId": "59",
    "joiningDate": "23-Jun-2025",
    "name": "Noria Noor",
    "modeOfWorking": "Remotely",
    "officialMail": "noria.noor@hostajournal.biz",
    "personalEmail": "nooriatahreem@gmail.com",
    "cnic": "32202-5500919-0",
    "whatsappPersonal": "92-323-1722017",
    "homePhone": "92-341-6669555",
    "address": "Burj Mahalam, Chak 35, Pattoki",
    "qualification": "MA English + B-ED",
    "gender": "Female",
    "endingDate": "31-04-2025",
    "experience": "Educators Teaching (March 2024)",
    "role": "Employee",
    "points": 0,
    "email": "nooriatahreem@gmail.com"
  },
  {
    "employeeId": "60",
    "joiningDate": "23-Jun-2025",
    "name": "Mehmoona Noor",
    "modeOfWorking": "Remotely",
    "assignments": "Remotely (30 Artcile Genarte + Formatting + Uplaoding)",
    "officialMail": "mehmoona.noor@hostajournal.biz",
    "personalEmail": "noormamoona7@gmail.com",
    "cnic": "32202-3635813-2",
    "whatsappPersonal": "92-329-7311713",
    "homePhone": "92-341-6669555",
    "address": "Burj Mahalam, Chak 35, Pattoki",
    "qualification": "BS(MATH)",
    "gender": "Female",
    "endingDate": "9-Aug-2025",
    "experience": "Educators Teaching (March 2025)",
    "role": "Employee",
    "points": 0,
    "email": "noormamoona7@gmail.com"
  },
  {
    "employeeId": "61",
    "joiningDate": "17-Jul-2025",
    "name": "Hafiz Tanveer Ahmad",
    "modeOfWorking": "ON Site",
    "assignments": "Canva (Cover Pages + Logo + CFP/CFT Designs) + Canva Video Designs (Pending)",
    "officialMail": "hafiztanveerdigital4060@gmail.com",
    "cnic": "35102-5353141-1",
    "whatsappPersonal": "92-301-4060230",
    "homePhone": "92-304-5664580",
    "address": "Asif Colony, Steert 2, Hallah Road, Pattoki",
    "qualification": "ICS",
    "gender": "Male",
    "endingDate": "8-Dec-2025",
    "experience": "1.5 Year Account Bahira Orchard",
    "role": "Employee",
    "points": 0,
    "email": "hafiztanveerdigital4060@gmail.com"
  },
  {
    "employeeId": "62",
    "joiningDate": "1-Aug-2025",
    "name": "Saim Adil",
    "officialMail": "saim.adil@hostajournal.biz",
    "personalEmail": "saimkhalil110@gmail.com",
    "cnic": "35103-9927807-7",
    "whatsappPersonal": "92-309-1722175",
    "homePhone": "92-304-8163622",
    "address": "Madina Colony Street No/01 Near Paragon School",
    "qualification": "Matric",
    "gender": "Male",
    "endingDate": "11-Jul-2025",
    "role": "Employee",
    "points": 0,
    "email": "saimkhalil110@gmail.com"
  },
  {
    "employeeId": "63",
    "joiningDate": "17-Aug-2025",
    "name": "Shakil Asghar",
    "modeOfWorking": "ON Site",
    "assignments": "50 Accounts CFP (Digital Marketing)",
    "personalEmail": "SHAKEELASGHAR771@GMAIL.COM",
    "cnic": "35103-6091838-1",
    "whatsappPersonal": "92-320-7371771",
    "homePhone": "92-302-4642811",
    "address": "Dholan Chak 07",
    "qualification": "I.Com",
    "gender": "Male",
    "endingDate": "29-Sep-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "SHAKEELASGHAR771@GMAIL.COM"
  },
  {
    "employeeId": "64",
    "joiningDate": "16-Aug-2025",
    "name": "Umair Waqas",
    "modeOfWorking": "ON Site",
    "officialMail": "umair.waqas@hostajournal.biz",
    "personalEmail": "alialso1823@gmail.com",
    "cnic": "35103-3782135-9",
    "whatsappPersonal": "92-327-0043093",
    "homePhone": "92-306-4216778",
    "address": "Zahid Housing Scheme, Pattoki",
    "gender": "Male",
    "endingDate": "5-Oct-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "alialso1823@gmail.com"
  },
  {
    "employeeId": "65",
    "joiningDate": "5-Nov-2025",
    "name": "Hifza Rafique",
    "modeOfWorking": "ON Site",
    "assignments": "Sent CFP + Submission Check + Emails Inbox",
    "officialMail": "hifzarafique12@gmail.com",
    "personalEmail": "hifzamam@gmail.com",
    "cnic": "35101-1723527-6",
    "whatsappPersonal": "92-344-0147180",
    "homePhone": "92-302-6808184",
    "address": "Kashif Chok Pattoki Near Barkat-e-Mustafa",
    "qualification": "BS Chemistry",
    "gender": "Female",
    "remarks": "🔑",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "hifzamam@gmail.com"
  },
  {
    "employeeId": "66",
    "joiningDate": "11-Nov-2025",
    "name": "Anisa Aslam",
    "modeOfWorking": "ON Site",
    "assignments": "Indexing",
    "officialMail": "anisaaslam678@gmail.com",
    "cnic": "35103-4427263-8",
    "whatsappPersonal": "92-316-6628720",
    "homePhone": "92-300-4146627",
    "address": "Gulshan Subhan Near Dar-e-Arkam School Pattoki",
    "qualification": "FSC-Medical",
    "gender": "Female",
    "endingDate": "13-Nov-2025",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "anisaaslam678@gmail.com"
  },
  {
    "employeeId": "67",
    "joiningDate": "11-Nov-2025",
    "name": "Raheen Shahbaz",
    "modeOfWorking": "ON Site",
    "assignments": "Citation + ",
    "officialMail": "raheenshahbaz6@g.mail.com",
    "personalEmail": "raheenshahbaz647@gmail.com",
    "cnic": "35103-5009720-0",
    "whatsappPersonal": "92-319-4511647",
    "homePhone": "92-303-0402187",
    "address": "Ghalan Chak no:9",
    "qualification": "FSC-Engineering",
    "gender": "Female",
    "remarks": "🔑",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "raheenshahbaz647@gmail.com"
  },
  {
    "employeeId": "68",
    "joiningDate": "11-Nov-2025",
    "name": "Ayesha Tariq",
    "modeOfWorking": "ON Site",
    "assignments": "Groups + Submission + Artcile Publication + Issue Publish",
    "officialMail": "ayeshatariq8836@gmail.com",
    "personalEmail": "ayeshatariq88991@gmail.com",
    "cnic": "35101-7677255-4",
    "whatsappPersonal": "92-309-4988991",
    "homePhone": "92-300-8836553",
    "address": "Changa Manga Bank Street House no:139",
    "qualification": "BS-English",
    "gender": "Female",
    "experience": "Navttc Jamber (HR Assistant) 6 Months",
    "role": "Employee",
    "points": 0,
    "email": "ayeshatariq8836@gmail.com"
  },
  {
    "employeeId": "69",
    "joiningDate": "11-Nov-2025",
    "name": "Hira Kahdim",
    "modeOfWorking": "ON Site",
    "assignments": "Indexing + Citation",
    "officialMail": "hirakhdim9272@gmail.com ",
    "personalEmail": "hirakhdim9272@gmail.com ",
    "cnic": "35103-4222683-0",
    "whatsappPersonal": "92-306-9548415",
    "homePhone": "92-321-7951663",
    "address": "Kashif Chok Pattoki Near Jamia Majid Shah Jmat",
    "qualification": "Intermediate F.A, Computer Diploma From GVTIW Pattoki",
    "gender": "Female",
    "role": "Employee",
    "points": 0,
    "email": "hirakhdim9272@gmail.com "
  },
  {
    "employeeId": "70",
    "joiningDate": "30-Dec-2025",
    "name": "Alia Sagheer",
    "modeOfWorking": "ON Site",
    "assignments": "Formatting + Uplaoding",
    "officialMail": "Sabasagheer552@gmail.com",
    "personalEmail": "sabasagheer00@gmail.com",
    "cnic": "35103-3320904-6",
    "whatsappPersonal": "92-311-1658519",
    "homePhone": "92-308-4365319",
    "address": "Bismillah City, Hallah Road Pattoki",
    "qualification": "I.COM, 1 year IT Diploma",
    "gender": "Female",
    "experience": "1.5 year teaching in Brilliant School, Hallah Road Pattoki",
    "role": "Employee",
    "points": 0,
    "email": "sabasagheer00@gmail.com"
  },
  {
    "employeeId": "71",
    "joiningDate": "30-Dec-2025",
    "name": "Saba Sagheer",
    "modeOfWorking": "ON Site",
    "assignments": "Old > New + ",
    "officialMail": "Sabasagheer552@gmail.com",
    "personalEmail": "sabasagheer00@gmail.com",
    "cnic": "35103-6450679-6",
    "whatsappPersonal": "92-311-1658520",
    "homePhone": "92-308-4365320",
    "address": "Bismillah City, Hallah Road Pattoki",
    "qualification": "FSC (Pre-Eng)",
    "gender": "Female",
    "experience": "1.5 year teaching in Brilliant School, Hallah Road Pattoki",
    "role": "Employee",
    "points": 0,
    "email": "sabasagheer00@gmail.com"
  },
  {
    "employeeId": "72",
    "joiningDate": "28-Jan-2026",
    "name": "Samana Batool",
    "modeOfWorking": "ON Site",
    "assignments": "CFP",
    "officialMail": "batoolsamana437@gmail.com",
    "personalEmail": "samanab998@gmail.com",
    "cnic": "35103-5959324-0",
    "whatsappPersonal": "92-308-2310465",
    "homePhone": "92-303-4033359",
    "address": "Pattoki Bilal Colony",
    "qualification": "ICS , BBA Continue University Of Okara",
    "gender": "Female",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "samanab998@gmail.com"
  },
  {
    "employeeId": "73",
    "joiningDate": "4-Feb-2026",
    "name": "Amina Mumtaz",
    "modeOfWorking": "ON Site",
    "assignments": "DOAJ / SCOPUS / WOS Publication",
    "personalEmail": "iaminamumtaz2002@gmail.com",
    "cnic": "35101-4487049-6",
    "whatsappPersonal": "92-310-6301496",
    "homePhone": "92-303-4069327",
    "address": "Gulshan Subhan Phase 1 Pattoki",
    "qualification": "BS-Education , Mphil-Education Continue",
    "gender": "Female",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "iaminamumtaz2002@gmail.com"
  },
  {
    "employeeId": "74",
    "joiningDate": "8-Feb-2026",
    "name": "Areeba Shahzad",
    "modeOfWorking": "ON Site",
    "officialMail": "areebashahzad200@gmail.com ",
    "personalEmail": "areebashahzad899@gmail.com",
    "cnic": "35101-2640220-6",
    "whatsappPersonal": "92-334-6437100",
    "homePhone": "92-335-6437100",
    "address": "Anwar Colony Near Kareem Park Mega Road",
    "qualification": "ICS , BBA Continue University Of Okara",
    "gender": "Female",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "areebashahzad899@gmail.com"
  },
  {
    "employeeId": "75",
    "joiningDate": "14-Feb-2026",
    "name": "Mehmona Mehmood",
    "modeOfWorking": "ON Site",
    "department": "Accounts",
    "personalEmail": "maimoonamahmood09@gmail.com",
    "cnic": "90403-0144555-4",
    "whatsappPersonal": "92-307-8832530",
    "homePhone": "92-308-4074571",
    "address": "Bilal Colony Pattoki",
    "qualification": "ICOM,ADP Accounting & Finance",
    "gender": "Female",
    "experience": "Fresh",
    "role": "Employee",
    "points": 0,
    "email": "maimoonamahmood09@gmail.com"
  },
  {
    "employeeId": "76",
    "joiningDate": "8-Feb-2026",
    "name": "Amina Afzal",
    "modeOfWorking": "ON Site",
    "gender": "Female",
    "role": "Employee",
    "points": 0,
    "email": "emp76@hostajournal.biz"
  },
  {
    "employeeId": "77",
    "joiningDate": "15-Feb-2026",
    "name": "Muqadas  Maid",
    "modeOfWorking": "ON Site",
    "cnic": "35103-7773414-8",
    "role": "Employee",
    "points": 0,
    "email": "emp77@hostajournal.biz"
  }
];

export const seedEmployees = async () => {
  const defaultPermissions = {
    approvalRequests: true,
    journals: true,
    indexingAgencies: true,
    publishers: true,
    hecApplications: true,
    issnRequests: true,
    doiManagement: true,
    dataTools: true,
    invoices: true,
    expenses: true,
    resources: true,
    notifications: true,
    employees: true,
    trash: true
  };

  for (const emp of employeeData) {
    try {
      await addDoc(collection(db, 'users'), {
        ...emp,
        permissions: defaultPermissions,
        createdAt: serverTimestamp()
      });
    } catch (error) {
      console.error(`Error adding employee ${emp.name}:`, error);
    }
  }
  console.log('Seeding completed!');
};
